name: Autograding Tests
'on': [push, pull_request]

jobs:
  autograding:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout student code
        uses: actions/checkout@v4
      
      - name: Download teacher's test repository
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}
        run: |
          git clone https://${{ secrets.PAT_TOKEN }}@github.com/IcensRAGHomework/assignment-tests.git temp-tests
          
      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Prepare tests
        run: |
          cp temp-tests/test_assignment.py .
    
      - name: Run tests and check for pass/fail
        id: test_step
        run: |
          if pytest test_assignment.py::test_add; then
            echo "SCORE=30" >> $GITHUB_ENV
          else
            echo "SCORE=0" >> $GITHUB_ENV
          fi

      - name: Display score
        run: echo "Final Score:${{ env.SCORE }}"
