name: Autograding Tests
'on': [push, pull_request]

jobs:
  autograding:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout student code
        uses: actions/checkout@v4
      
      - name: Download teacher's test repository
        env:
          GITHUB_TOKEN: ${{ secrets.ORG_PAT_TOKEN }}
        run: |
          git clone https://${{ secrets.ORG_PAT_TOKEN }}@github.com/IcensRAGHomework/assignment-tests-.git temp-tests
          
      - name: Cache pip dependencies
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dependencies
        run: |
          if ! pip check; then
            pip install --cache-dir ~/.cache/pip -r requirements.txt
          else
            echo "All dependencies are already satisfied."
          fi

      - name: Prepare tests
        run: |
          cp temp-tests/test_assignment.py .
    
      - name: Run tests and check for pass/fail
        id: test_step
        run: |
          if pytest test_assignment.py::test_add; then
            echo "SCORE=30" >> $GITHUB_ENV
          else
            echo "SCORE=0" >> $GITHUB_ENV
          fi

      - name: Display score
        run: echo "Final Score:${{ env.SCORE }}"
